### ISSUE TITLE
List open issues command?

### ISSUE THREAD

**Issue by alichtman** [victorgama/gh#1]
Possible to add a CLI option to list open issues?

**Comment by heyvito** [comment]
Hi @alichtman! It is possible, but right now I don't have spare time to work on this project.
Feel free to open a PR! :)

**Comment by alichtman** [comment]
I've been meaning to learn Go at some point, so whenever I get around to that, I'll add this functionality.

**Comment by alichtman** [comment]
https://github.com/stephencelis/ghi

This is a good replacement for this feature.
